### ISSUE TITLE
password missing

### ISSUE THREAD

**Issue by Intermarch3** [EpitechMouliBot/browser-extension#11]
![image](https://github.com/EpitechMouliBot/browser-extension/assets/78302154/b7862991-5716-4ff3-bb95-4a596833b59e)
Get this error but I did set a password.

**Comment by RedBoardDev** [comment]
Hello, this error will be fix soon as possible. I will reply here when it's done

**Comment by RedBoardDev** [comment]
Hello !
This error is fix. The server was down. I've had notification by e-mail by default and you can setup discord if you want :)

**Comment by Intermarch3** [comment]
nice, thank you.
Let's try it
