### ISSUE TITLE
Unable to login and create a new account

### ISSUE THREAD

**Issue by Enoal-Fauchille-Bolle** [EpitechMouliBot/browser-extension#13]
It always says "Invalid password" when login and "Account already exist" when creating a new account
How can we reset password ???

**Comment by RedBoardDev** [comment]
Hello !
You actualy can't reset your password.
The epitechmoulibot is actualy in complet rework and I will think about implement a button to reset your password using e-mail. But actualy, I purposed you to recreate a new account or wait for the new bot.

**Comment by AstralRedshift** [comment]
Ok thanks, so it's normal that i cannot login ?
![image](https://github.com/EpitechMouliBot/browser-extension/assets/73392042/d873c85f-37c4-4f01-a848-15d5296a0236)

**Comment by RedBoardDev** [comment]
Sorry for the delay.
Yes, it was down. I've updated everything, update the extension ans create a new account.
Everything work now !

**Comment by Enoal-Fauchille-Bolle** [comment]
Nice !!!!
How can I use it now ?

**Comment by RedBoardDev** [comment]
Like before this update.
Download the extension: https://chromewebstore.google.com/detail/epitech-mouli-bot/njgkdlhcpojpejgbcfadnmnlphfpcdpi?hl=fr

And then, just create an account on this extension and select what do you prefer: email, discord, ntfy.sh
Discord will be available next week I think

**Comment by Enoal-Fauchille-Bolle** [comment]
Thank you very much 👍

**Comment by Igoatyouu** [comment]
It seems like it's down again
Is it on my side or is it really down?

**Comment by RedBoardDev** [comment]
> It seems like it's down again Is it on my side or is it really down?

Hello, it's probably because of the new server. Could you please retry now ? I think that was because some DNS was not correct actualy.
But do not hesitate to open an issue if something wrong, it's a new server, and complete new project so it can be possible to see some bug
